name: Deploy to Dokku

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show 5 most recent commits
        run: git log --oneline -n 5

      - name: Deploy to GCE via dokku
        uses: dokku/github-action@master
        with:
          trace: 1
          branch: main
          git_push_flags: --force
          git_remote_url: ${{ secrets.DOKKU_GIT_REMOTE_URL }}
          ssh_host_key: ${{ secrets.DOKKU_SSH_HOST_KEY }}
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
